# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-installer

# >> macros
# << macros

Summary:    Maui Installer
Version:    0.1.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        https://github.com/mauios/maui-installer.git
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-installer.yaml
Requires:   calamares
BuildRequires:  cmake

%description
Maui modules and configuration for Calamares.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/calamares/*
# >> files
# << files
